<a href="https://colab.research.google.com/github/Joeaviator/DECISION-TREE-HW/blob/main/DECISION_TREE_HW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report

In [2]:
from google.colab import files
file = files.upload()

Saving Iris Data.csv to Iris Data.csv

In [3]:
df=pd.read_csv('Iris Data.csv')
df.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [4]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [7]:
x=df.drop('species',axis=1)
y=df['species']

In [8]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [9]:
model=DecisionTreeClassifier()
print("Model Loaded Successfully")

Model Train Successfully

In [12]:
model.fit(x_train,y_train)
print("Model Trained Successfully")

Model Trained Successfully

In [13]:
preds=model.predict(x_test)
print("Model Has Predicted Sucessfully")

Model Has Predicted Sucessfully

In [14]:
pd.DataFrame({'Actual Values': y_test, 'Predicted Values':preds})

       Actual Values Predicted Values
73   Iris-versicolor  Iris-versicolor
18       Iris-setosa      Iris-setosa
118   Iris-virginica   Iris-virginica
78   Iris-versicolor  Iris-versicolor
76   Iris-versicolor  Iris-versicolor
31       Iris-setosa      Iris-setosa
64   Iris-versicolor  Iris-versicolor
141   Iris-virginica   Iris-virginica
68   Iris-versicolor  Iris-versicolor
82   Iris-versicolor  Iris-versicolor
110   Iris-virginica   Iris-virginica
12       Iris-setosa      Iris-setosa
36       Iris-setosa      Iris-setosa
9        Iris-setosa      Iris-setosa
19       Iris-setosa      Iris-setosa
56   Iris-versicolor  Iris-versicolor
104   Iris-virginica   Iris-virginica
69   Iris-versicolor  Iris-versicolor
55   Iris-versicolor  Iris-versicolor
132   Iris-virginica   Iris-virginica
29       Iris-setosa      Iris-setosa
127   Iris-virginica   Iris-virginica
26       Iris-setosa      Iris-setosa
128   Iris-virginica   Iris-virginica
131   Iris-virginica   Iris-virginica
145   Iris-virginica   Iris-virginica
108   Iris-virginica   Iris-virginica
143   Iris-virginica   Iris-virginica
45       Iris-setosa      Iris-setosa
30       Iris-setosa      Iris-setosa

In [15]:
accuracy_score(y_test, preds)

1.0

In [16]:
classification=classification_report(y_test,preds)
print(classification)

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30